"SESSION_ID = VAJIRA-MD=jQdwUYgQ#F2EG8XJMzqsubHHfGMBBOgNQg4jZfWU2MtrZaQ7XauU
STICKER_PACKNAME = LyFE
ALWAYS_ONLINE = false
RMBG_KEY = null
LANGUAG = en
WARN_LIMIT = 3
FORCE_LOGOUT = false
BRAINSHOP = 159501,6pq8dPiYt7PdqHz3
MAX_UPLOAD = 200
REJECT_CALL = false
SUDO = +917679502671
TZ = Asia/Kolkata
VPS = true
AUTO_STATUS_VIEW = true
SEND_READ = false 
AJOIN = false
DISABLE_START_MESSAGE = false
PERSONAL_MESSAGE = null" > config.env
